server:
  addr: "127.0.0.1:8080"
  public_base_url: ""

database:
  driver: "sqlite"
  sqlite_path: "./data/hub.db"
  postgres_dsn: ""

providers:
  rekor:
    enabled: true
    token: "Rekor_2025"
    share_defaults:
      plate: true
      timestamp: true
      camera_name: true
      confidence: true
      gps: false
      images: false
    index_fields:
      - plate
      - confidence
      - region
      - camera.name
      - vehicle.color
      - vehicle.make
      - vehicle.model
      - gps.lat
      - gps.lon
    images:
      base_url: "https://police.openalpr.com"
      path_template: "/img/{agent_uid}/{uuid}.jpeg?api_key=${REKOR_API_KEY}"
      fetch_enabled: true
      auth_header: "env REKOR_API_KEY=e397c9079becc818068b7fc9746a50b1850280a7"